os: Visual Studio 2015
build: off

before_test:
  - dotnet --info
  - dotnet restore

test_script:
  # Build sample
  - dotnet build -c Release samples/Channels.Samples

after_test:
  # Build and pack source
  - dotnet pack -c Release src/Channels --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release src/Channels.Networking.Libuv --version-suffix %APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release src/Channels.Networking.Windows.RIO --version-suffix %APPVEYOR_BUILD_NUMBER%

artifacts:
  path: '**/*.nupkg'

deploy:  
- provider: NuGet
  server: https://www.myget.org/F/channels/api/v2/package
  api_key:
    secure: OvE2o5re489/Dr0nt3p9UzpcIcLhSt7FoHyvRUuniUbj5Wkx9+i9fBYuwmDGtxnw
  skip_symbols: true
  on:
    branch: master
